### ISSUE TITLE
Tracking: input/output

### ISSUE THREAD

**Issue by nathanin** [KnottLab/codex#9]
For a command-line interface we want a `preprocess` command like:

```bash
$ codex preprocess /raw/data --name sample --region 1 -o /output/dir
```

Should create `/output/dir` and 
- [ ] place preprocessed images under `/output/dir/images`
- [ ] make a record of arguments, intermediate files/settings at `/output/dir/settings.txt`
- [ ] QC metrics under `/output/dir/qc`
